version: '3'

services:
  web:
    build:
      context: .
    container_name: wcyd
    ports:
      - "8080:80"
    depends_on:
      - db
    

  api:
    build:
      context: ./api
    container_name: api_server
    expose:
      - "5000"
    
  db:
    image: mysql:8.0
    volumes:
      - mysql_db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: date
      MYSQL_USER: date
      MYSQL_PASSWORD: somepassword
    ports:
      - 5000:3306

volumes:
  mysql_db: